### ISSUE TITLE
Errors with OSHGui

### ISSUE THREAD

**Issue by CovERUshKA** [KN4CK3R/OSHGui#13]
Two more errors(in my project)
![image](https://user-images.githubusercontent.com/43516399/58710413-f0e6d880-83c4-11e9-9cc7-39b4801f23bc.png)

_Originally posted by @CovERUshKA in https://github.com/KN4CK3R/OSHGui/issues/12#issuecomment-497717695_

**Comment by KN4CK3R** [comment]
Please checkout a new copy of the code. Build the dependecy projects and then try to compile the sample project. If it doesn't work please report back. At the moment I think you made a mistake somewhere because it is working for me.

**Comment by CovERUshKA** [comment]
I just set in settings "Conformance mode" to No and all works.
![image](https://user-images.githubusercontent.com/43516399/58745492-681a7c00-845a-11e9-8033-5b4156eaa523.png)
