### ISSUE TITLE
Can't set viewports

### ISSUE THREAD

**Issue by alphauc** [KN4CK3R/OSHGui#14]
Hi! 
I ran into an issue when using the current OSHGui renderer. I'm currently calling SetViewport( ) to try and clip an area, but it seems not to work.
The renderer I'm using can be found here: https://github.com/EternityX/DEADCELL-CSGO/blob/master/deadcell/oshgui/renderer.cpp
My only addition to that renderer is the `get_device( )` function that simply returns the device.

Here is my code:
```cpp
//	store original viewport to restore later
D3DVIEWPORT9 original_viewport;
g_renderer.get_device( )->GetViewport( &original_viewport );

//	clip at position (100, 100), with size (50, 50) 
D3DVIEWPORT9 clip = { 100, 100, 50, 50 };
g_renderer.get_device( )->SetViewport( &clip );

g_renderer.filled_rect( OSHGui::Drawing::Color::White( ), 100, 100, 500, 500 );

//	restore
g_renderer.get_device( )->SetViewport( &original_viewport );
```
Here is the outcome:
![image](https://user-images.githubusercontent.com/43868994/62119364-4b15f400-b2b7-11e9-8e42-44b191a011f4.png)

Is there any way anyone could point me into the right direction, on how I could/should go about this? 
Thanks 👍

**Comment by KN4CK3R** [comment]
Your viewport gets overriden while drawing. Use the `SetArea` method of the `Direct3D9RenderTarget` class (https://github.com/KN4CK3R/OSHGui/blob/master/Drawing/Direct3D9/Direct3D9RenderTarget.hpp#L73) and let me know if this works for you.

**Comment by alphauc** [comment]
> Your viewport gets overriden while drawing. Use the `SetArea` method of the `Direct3D9RenderTarget` class (https://github.com/KN4CK3R/OSHGui/blob/master/Drawing/Direct3D9/Direct3D9RenderTarget.hpp#L73) and let me know if this works for you.

Thanks for the reply. I've adjusted my code and tried what you suggested, yet it still yields the same result. Here is my current code:
```cpp
//	store original area to restore later
OSHGui::Drawing::RectangleF original_area =
	g_renderer.get_render_target( )->GetArea( );

//	clip at position (100, 100), with size (50, 50) 
OSHGui::Drawing::RectangleF clip = OSHGui::Drawing::RectangleF(
	OSHGui::Drawing::PointF( 100, 100 ), OSHGui::Drawing::SizeF( 50, 50 ) );

g_renderer.get_render_target( )->SetArea( clip );

g_renderer.filled_rect( OSHGui::Drawing::Color::White( ), 100, 100, 500, 500 );

//	restore
g_renderer.get_render_target( )->SetArea( original_area );
```
Any ideas?
Thanks 👍

**Comment by KN4CK3R** [comment]
I have tested it without problems in the sample project:
![grafik](https://user-images.githubusercontent.com/1666336/62162600-e7241780-b318-11e9-8289-a0d2ddc22c00.png)
As you can see the form titlebar is clipped.

**Comment by alphauc** [comment]
Interesting, if this helps, what I'm precisely trying to do is set a clip to the position and size of a groupbox in my menu, to apply scrolling and to prevent from controls going out of bounds of the groupbox. 
Here is a screenshot explaining what i'm trying to do, as (I'm not sure) you might be getting me wrong. 
![image](https://user-images.githubusercontent.com/43868994/62163292-fbb0e180-b311-11e9-92f8-9ddc869dadad.png)

But what is actually happening, is this: 
![image](https://user-images.githubusercontent.com/43868994/62163379-20a55480-b312-11e9-89d9-006cd2926e15.png)

I hope you can understand better what I'm trying to do. I've tried doing SetArea to some random coordinates and while it seemed to work, as soon as I restored the original area, everything went back to normal and nothing was being clipped.

**Comment by KN4CK3R** [comment]
There is a reason this feature is not implemented already. 😄 You may have more luck with the `SetClippingActive` of the `GeometryBuffer` class. But you would need to force the child elements to use the `GeometryBuffer` of the `GroupBox`. This is not implemented yet. If you want to try to implement it, I would design it like this:
`Control::BufferGeometry` calls a method like `GetParentGeometryBuffer`. This call bubbles up in the control tree to get a buffer. The root may be the form. The `GroupBox` may have a buffer which is clipped to the "client rectangle" (the contained panel). Every child draws itself into this buffer and gets automaticly clipped. There may be fine tuning needed for some controls like the `ComboBox`. The expanded list should not be clipped by the form for example.

**Comment by alphauc** [comment]
> There is a reason this feature is not implemented already. 😄 You may have more luck with the `SetClippingActive` of the `GeometryBuffer` class. But you would need to force the child elements to use the `GeometryBuffer` of the `GroupBox`. This is not implemented yet. If you want to try to implement it, I would design it like this:
> `Control::BufferGeometry` calls a method like `GetParentGeometryBuffer`. This call bubbles up in the control tree to get a buffer. The root may be the form. The `GroupBox` may have a buffer which is clipped to the "client rectangle" (the contained panel). Every child draws itself into this buffer and gets automaticly clipped. There may be fine tuning needed for some controls like the `ComboBox`. The expanded list should not be clipped by the form for example.

Thanks for the feedback! I'll try and make that work, hopefully this should resolve my issue. :)

**Comment by KN4CK3R** [comment]
If you get it to work please make a pull request. And if you need help just ask.
