### ISSUE TITLE
Can't remove controls

### ISSUE THREAD

**Issue by sharky1001** [KN4CK3R/OSHGui#15]
I have a basic form, consisting of few pictureboxes and labels. I added a button and I'm doing this in it's click handler:

`this->RemoveControl(label_CurrentPage);`

The code is being executed, however, the label is not removed. No error, nothing.
After removing, I'm also iterating over GetControls() to check the current controls and it's still there.

**Comment by KN4CK3R** [comment]
Thank you for the report.
```cpp
auto form = std::make_shared<Form>();

auto button = new Button();
button->GetClickEvent() += ClickEventHandler([form](auto sender)
{
	form->RemoveControl(sender);
});
form->AddControl(button);
```
This works now as expected.

**Comment by sharky1001** [comment]
Thanks for the quick fix @KN4CK3R !

However this change broke many things in my app, now I'm getting random crashes everywhere :/

**Comment by KN4CK3R** [comment]
Are you sure the reason is the change (because it just redirects a call)? Do you have an example?

**Comment by sharky1001** [comment]
I am sure, undoing the changes solve it. 
But it's probably because of my modification to the original code. I added something like this, and been using it for a while:

![Screenshot_3](https://user-images.githubusercontent.com/51142000/66256695-3a8f6780-e799-11e9-9245-4bcf0abcb244.png)

This is to make my windows fit the original game UI (I'm working on an old 2005 game). And calling this right after everything is added to the form. (At the end of InitializeComponent())

`this->CorrectizeCaptionBar();`

**Comment by KN4CK3R** [comment]
Yes, your changes are the crash reason. Replace your code with this and it should work:

```diff
- this->RemoveControl(captionBar_);
+ Control::RemoveControl(captionBar_);
```

**Comment by sharky1001** [comment]
Yes, that solved it. Thanks alot again, awesome library 💯

**Comment by sharky1001** [comment]
Hey @KN4CK3R , I know I'm being too much, and didn't want to create an issue for something like this. But is there a way to change the opacity of an image PictureBox?

**Comment by KN4CK3R** [comment]
No, but you could change the opacity of the image. If thats not possible the renderer must be changed to use alpha blending.

**Comment by sharky1001** [comment]
When I added a button to GUI on runtime I wanted to make it come smoothly (like a fade-in). And for that I need to make hundreds of images that way... It's not that important, was mostly out of curiousity. I'll have a look on alpha blending.
