### ISSUE TITLE
OSHGui for DirectX 7?

### ISSUE THREAD

**Issue by Montrii** [KN4CK3R/OSHGui#27]
So i'm currently working on a menu for the game "Gothic 1", which is relying on DirectX 7 for drawing.

Unfortunately, other UI librarys such as ImGui or nuklear do not support rendering using DirectX7.
However, by simply looking at this UI, it should (Direct3D7Renderer).

So i simply downloaded the main branch, compiled the /Dependencies and attempted to rewrite the OSHGui Hook Dll with DirectX7 Support.

However, that does not quite work. 

For some reason this code:

```c++
	// 1. create our renderer, Direct3D9 in this case
	-> auto renderer = std::make_unique<Direct3D7Renderer>(device);
	
	// 2. and initialize the OSHGui with it
	Application::Initialize(std::move(renderer));
```

breaks every single time. It won't let me compile the code with the following error message:

"Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __thiscall OSHGui::Drawing::Direct3D7Renderer::Direct3D7Renderer(struct IDirect3DDevice7 *)" (??0Direct3D7Renderer@Drawing@OSHGui@@QAE@PAUIDirect3DDevice7@@@Z)	OSHGui Hook DLL	C:\Users\XXXX\Desktop\OSHgui\OSHGui-master\Projects\VS2019\OSHGui_Hook_Sample.obj	1	
"

Would you be able to provide me a solution for using the Direct3D7Renderer?
I really would like to use a UI that i can make work internally.
I am trying the hardest to avoid external and also using the GDI Implementation of ImGUI, as it is eating performance alot.

Thanks.

**Comment by KN4CK3R** [comment]
You have to add the `Direct3D7xxx.cpp` files to your project as they are not compiled into the library. Have a look at the sample project (files):
https://github.com/KN4CK3R/OSHGui/blob/2c23ee267a5e239ef74f2038271c548b082c10a5/Projects/VS2019/OSHGui_Sample.vcxproj#L22-L27

**Comment by Montrii** [comment]
I did that.
![Screenshot_1605](https://github.com/KN4CK3R/OSHGui/assets/69902394/f8406bcb-d549-4667-b8b6-7fed2ea0d60b)


![Screenshot_1606](https://github.com/KN4CK3R/OSHGui/assets/69902394/6d1ee869-7aed-4fe1-93c5-ad4b0803c8f6)

Which in turn wants me to include "d3d8.h".

Including Direct X 8 libs and includes, another compile causes these errors:


![Screenshot_1607](https://github.com/KN4CK3R/OSHGui/assets/69902394/84680410-2b96-42c1-922d-054fba030ed6)

However in this case, i already have all these affected files added in the project.

**Comment by KN4CK3R** [comment]
Hm, looks like I forgot to change that. You could exchange that include with `ddraw.h` and test it again.

**Comment by Montrii** [comment]
Adjusted, same last error as before. (Last screenshot)
Was this D3D7 ever actually tested? i've seen ENYZMEX V1.2 claiming its running on D3D7 with OSHGui, but cant really see the implementation of this, as i only found one compiled version.

**Comment by KN4CK3R** [comment]
I think I used it with Unreal 1 but that was 6 years ago. Don't know if I have the code from back then because I did not publish something for DX7.

**Comment by Montrii** [comment]
I mean it would be great, as i really would like to use this repo for my project.
I might aswell update the d3d7 in case you did something different.

However, what could the error i posted be caused by?

**Comment by KN4CK3R** [comment]
Still working:
![grafik](https://github.com/KN4CK3R/OSHGui/assets/1666336/f02b9130-a4b8-4582-b4e8-0e7805543611)

You need to link
```
dxguid.lib
ddraw.lib
d3dim.lib
d3dx.lib
```
and change the include
`#include <ddraw.h>`

**Comment by Montrii** [comment]
![Screenshot_1609](https://github.com/KN4CK3R/OSHGui/assets/69902394/08ba4e99-53c6-475d-ae2c-9b64bcc604f5)
![Screenshot_1610](https://github.com/KN4CK3R/OSHGui/assets/69902394/f3e18d74-bdda-4189-aca3-bbdadf400e3b)

Still same error.

Even built the static library with includes and new libs again, still same error.

**Comment by Montrii** [comment]
Aight so little update, i set up the project one more time and successfully got the Hook DLL compiled with a functioning d3d7renderer.

![Screenshot_1611](https://github.com/KN4CK3R/OSHGui/assets/69902394/366af075-0d5d-487f-bf0c-0ebfc4386405)


Since D3D7 has no Reset Function, i assume the game is crashing whenever you are resetting the device for a different resolution etc.

However, the game does run with a UI.

I now attempt to implement this UI into my existing internal and will keep you updated in this case this might need some adjusting.

It would be great if you could show me how you used the Sample Project to render with d3d7, as d3d7 does not have a -Present function either for example.

**Comment by KN4CK3R** [comment]
My sample project is not feature complete. I did not implement "reset" like behaviour. For DX7 you should use the `IsLost()` method to query if the device was lost and then `Restore()` it.

Edit:
https://learn.microsoft.com/en-us/windows/win32/api/ddraw/nf-ddraw-idirectdrawsurface7-islost
https://learn.microsoft.com/en-us/windows/win32/api/ddraw/nf-ddraw-idirectdrawsurface7-restore
https://learn.microsoft.com/en-us/windows/win32/api/ddraw/nf-ddraw-idirectdraw7-testcooperativelevel
https://learn.microsoft.com/en-us/windows/win32/api/ddraw/nf-ddraw-idirectdraw7-restoreallsurfaces

**Comment by Montrii** [comment]
Aight, well the implementation into my existing dll worked just fine, therefore this can be closed.
