### ISSUE TITLE
Missing SimpleImageLoader.hpp and ft2build.h

### ISSUE THREAD

**Issue by ghost** [KN4CK3R/OSHGui#6]
Hi I am trying to use this GUI but when I try to compile the Static Library but I get these errors.
![b62ee2e3c4e6250f5c21d1eee4a29252](https://user-images.githubusercontent.com/28850156/35486755-937259fe-0440-11e8-908c-811770cb9810.png)

**Comment by KN4CK3R** [comment]
You need to build the dependencies first in /Dependencies/Source. This will create the needed files.

**Comment by ghost** [comment]
I guess that I am blind thank you very much 💃 It worked

**Comment by KN4CK3R** [comment]
Not your fault, haven't published much instructions. 😕

**Comment by ghost** [comment]
Ye. Thanks for the help though :D
