### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by ghost** [KN4CK3R/OSHGui#7]
If I set DefaultColor.BackColor(_Drawing::Color(255, 245, 208, 255)_), It will give me a white window.
Any ideas to fix 😭 
![image](https://user-images.githubusercontent.com/16219523/36932666-7f813046-1f07-11e8-9300-60d288a424dc.png)
```cpp
auto form = std::make_shared<OSHGui::Form>();

form->SetName("form1");
form->SetText("Form1");

Drawing::Style theme;
theme.DefaultColor.ForeColor = Drawing::Color(255, 31, 97, 106);
theme.DefaultColor.BackColor = Drawing::Color(255, 245, 208, 255);
#define MakeTheme(control, color1, color2) theme.SetControlColorTheme(control, Drawing::Theme::ControlTheme(color1, color2))

form->ApplyStyle(theme);
```

**Comment by KN4CK3R** [comment]
You use the Color constructor in a wrong way. The constructor takes floats in the range [0...1] but it looks like you are using the range [0...255]. There is a special converter function for this usecase:
```
theme.DefaultColor.ForeColor = Color::FromARGB(255, 31, 97, 106);
theme.DefaultColor.BackColor = Color::FromARGB(255, 245, 208, 255);
```

![grafik](https://user-images.githubusercontent.com/1666336/36933930-a25e6050-1ee1-11e8-87c4-49d79f21f154.png)

Was this code generated by OSHVisualGui? ~~If yes, then this is a bug in the generator.~~ Tested the generator which generates the correct code.

**Comment by ghost** [comment]
It's working, thanks.
Yeah, it's from OSHVisualGui.
By the way, do you wanna remake OSHVisualGui? please.
it's too old.

**Comment by KN4CK3R** [comment]
That's no reason to recreate it.
